repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.11.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
  -   repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.0.0-alpha.2
      hooks:
        -   id: eslint
            additional_dependencies:
              - eslint-plugin-hydrogen@0.12.2
  -   repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
        -   id: prettier
